import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {build} from 'esbuild';
import {readFileSync,mkdirSync} from 'node:fs';
const pg=new PGlite();
process.env.DB_DRIVER='postgres';
process.env.DATABASE_URL='postgresql://test:test@localhost/test';
globalThis.__accountQuery=async(sql,values)=>{const r=await pg.query(sql,values);return {rows:r.rows,rowCount:r.affectedRows??r.rows.length}};
mkdirSync('.sites-runtime/account-tests',{recursive:true});
await build({stdin:{contents:"export * as account from './app/api/account/route';export * as session from './app/api/session/route';export * as profile from './app/api/profile/route';export * as engine from './lib/game/engine';export * as storage from './lib/room-storage';",resolveDir:process.cwd(),loader:'ts'},outfile:'.sites-runtime/account-tests/routes.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'test-postgres',setup(b){b.onResolve({filter:/^pg$/},()=>({path:'pg',namespace:'test-pg'}));b.onLoad({filter:/.*/,namespace:'test-pg'},()=>({contents:'export class Pool { on(){} query(sql,values){return globalThis.__accountQuery(sql,values)} }'}));b.onResolve({filter:/^@neondatabase\/serverless$/},()=>({path:'db',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const neon=()=>({query:globalThis.__accountQuery});'}))}}]});
const {account,session,profile,engine,storage}=await import('../.sites-runtime/account-tests/routes.mjs');
await pg.exec(readFileSync('db/postgres.sql','utf8'));
async function call(group,cookie,body){const req=new Request('https://game.test/api/test',{method:body?'POST':'GET',headers:{cookie:cookie??'',...(body?{'Content-Type':'application/json',Origin:'https://game.test'}:{})},body:body?JSON.stringify(body):undefined});const r=await group[req.method](req);return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0],setCookie:r.headers.get('set-cookie')}}
await test('Accounts, remembered sessions, private profiles and PostgreSQL result lifecycle',async t=>{
 let guest,a,b;
 await t.test('guest gets a random remembered identity without entering a name',async()=>{guest=await call(session);assert.equal(guest.status,200);assert.match(guest.data.name,/^Guest_\d+$/);assert.match(guest.setCookie,/HttpOnly/);assert.match(guest.setCookie,/Secure/);assert.match(guest.setCookie,/Max-Age=1577880000/);assert.equal((await call(session,guest.cookie)).data.id,guest.data.id)});
 await t.test('registration preserves guest identity, hashes password and rotates session',async()=>{a=await call(account,guest.cookie,{op:'register',username:'Player_One',name:'সাহিম',password:'a-secret-password',remember:true});assert.equal(a.status,200,JSON.stringify(a));assert.equal(a.data.id,guest.data.id);assert.equal(a.data.username,'player_one');assert.notEqual(a.cookie,guest.cookie);const row=(await pg.query('SELECT * FROM accounts')).rows[0];assert.notEqual(row.password_hash,'a-secret-password');assert.equal(row.password_hash.length,64);assert.equal((await call(profile,guest.cookie)).status,401);assert.equal((await call(profile,a.cookie)).data.username,'player_one')});
 await t.test('duplicate case-insensitive username, wrong passwords and cross-origin requests rejected',async()=>{b=await call(session);const bad=await call(account,b.cookie,{op:'login',username:'PLAYER_ONE',password:'wrong-password'});assert.equal(bad.status,400);const duplicate=await call(account,b.cookie,{op:'register',username:'PLAYER_ONE',name:'Other',password:'a-secret-password'});assert.equal(duplicate.status,400);const r=await account.POST(new Request('https://game.test/api/account',{method:'POST',headers:{cookie:b.cookie,'Content-Type':'application/json',Origin:'https://evil.test'},body:JSON.stringify({op:'login',username:'player_one',password:'a-secret-password'})}));assert.equal(r.status,400)});
 await t.test('second device logs in as same player; non-remembered login has session cookie',async()=>{b=await call(account,b.cookie,{op:'login',username:'PLAYER_ONE',password:'a-secret-password',remember:false});assert.equal(b.status,200);assert.equal(b.data.id,a.data.id);assert.ok(!b.setCookie.includes('Max-Age'));assert.equal((await call(profile,b.cookie)).data.id,a.data.id);assert.equal((await call(profile,a.cookie)).status,200)});
 await t.test('expired token cannot authenticate; logout revokes only this device',async()=>{const token=b.cookie.split('=')[1];const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),v=>v.toString(16).padStart(2,'0')).join('');await pg.query('UPDATE login_tokens SET expires=0 WHERE token_hash=$1',[hash]);assert.equal((await call(profile,b.cookie)).status,401);const loggedOut=await call(account,a.cookie,{op:'logout'});assert.equal(loggedOut.status,200);assert.match(loggedOut.data.name,/^Guest_/);assert.equal((await call(profile,a.cookie)).status,401);a=await call(account,loggedOut.cookie,{op:'login',username:'player_one',password:'a-secret-password',remember:true});assert.equal(a.status,200)});
 let g;
 await t.test('server tracks real bluffs and successful/failed challenges without leaking them',async()=>{g=engine.newGame('STAT22','Stats room',false,2,a.data.id,'Sahim');g.players.push({id:'other-player',name:'Other',coins:2,cards:[],ready:true});g.players[0].ready=true;engine.start(g);g.players[0].cards=[{role:'orun',alive:true},{role:'kalu',alive:true}];g.players[1].cards=[{role:'bir',alive:true},{role:'kalu',alive:true}];engine.act(g,a.data.id,{action:'bir'});engine.respond(g,'other-player',{choice:'pass'});assert.equal(g.roundMetrics[a.data.id].bluffs,1);engine.act(g,'other-player',{action:'bir'});engine.respond(g,a.data.id,{choice:'challenge'});assert.equal(g.roundMetrics[a.data.id].challenges,1);assert.equal(g.roundMetrics[a.data.id].challengeWins,0);engine.respond(g,a.data.id,{choice:'lose',index:0});engine.act(g,a.data.id,{action:'bir'});engine.respond(g,'other-player',{choice:'challenge'});assert.equal(g.roundMetrics['other-player'].challengeWins,1);engine.respond(g,a.data.id,{choice:'lose',index:1});assert.equal(g.status,'finished');assert.equal(engine.view(g,'other-player').roundMetrics,undefined)});
 await t.test('atomic result ledger ignores stale saves and counts finished round once',async()=>{await pg.query('INSERT INTO rooms (code,name,private,state,revision,updated) VALUES ($1,$2,0,$3,0,$4)',[g.code,g.name,JSON.stringify({...g,status:'playing'}),Date.now()]);assert.equal((await storage.saveGame(g,10)).meta.changes,0);assert.equal((await pg.query('SELECT * FROM player_results')).rows.length,0);assert.equal((await storage.saveGame(g,0)).meta.changes,1);assert.equal((await storage.saveGame(g,1)).meta.changes,1);const stats=(await call(profile,a.cookie)).data.stats;assert.deepEqual(stats,{games:1,wins:0,bluffs:1,challenges:1,challengeWins:0});assert.equal((await pg.query('SELECT * FROM player_results')).rows.length,2);assert.equal((await call(profile)).status,401)});
 await t.test('rematch gets unique round id even after a new series',async()=>{const old=g.roundId;engine.prepareRematch(g);g.players.forEach(p=>p.ready=true);engine.start(g);assert.notEqual(g.roundId,old);assert.equal(g.roundMetrics[a.data.id].bluffs,0)});
 await t.test('cleanup removes stale lobbies/results, retains playing and active rooms and statistics',async()=>{await pg.query('DELETE FROM rooms');const now=Date.now();for(const [code,status,age] of [['WAIT22','waiting',3*3600000],['DONE22','finished',25*3600000],['LIVE22','playing',10*86400000],['HERE22','waiting',1000]])await pg.query('INSERT INTO rooms (code,name,private,state,updated,last_active) VALUES ($1,$1,0,$2,$3,$3)',[code,JSON.stringify({...g,code,status}),now-age]);await storage.cleanAbandonedRooms(now);assert.deepEqual((await pg.query('SELECT code FROM rooms ORDER BY code')).rows.map(r=>r.code),['HERE22','LIVE22']);assert.equal((await call(profile,a.cookie)).data.stats.games,1);assert.equal(storage.roomExpired({state:JSON.stringify({...g,status:'playing'}),updated:0}),false)});
 await t.test('login rate limit is shared across fresh guest sessions for the same username',async()=>{let last;for(let i=0;i<9;i++){const fresh=await call(session);last=await call(account,fresh.cookie,{op:'login',username:'missing_user',password:'a-wrong-password'});}assert.match(last.data.error,/১৫ মিনিট/)});
});
await pg.close();
