'use client';
import {useEffect,useRef,useState} from 'react';
import type {Game} from '@/lib/game/engine';
const LINES:Record<string,string[]>={bir:['বীরবিক্রমের নাম শুনেছ? তিন কয়েন এখন আমার ঝুলিতে!','সাহস থাকলে challenge করো—বীরবিক্রম পিছু হটে না।'],mamdo:['মামদোহামদ বলছি—ভাগের কয়েনটা ভুলে যেও না!','মামদোহামদের দাবিতে হিসাবও আছে, হাসিও আছে!'],orun:['ঊরণের চোখ এড়ায় কিছুই না—ডেক থেকে দেখি ভাগ্যে কী আছে!','একটা বদলেই হয়তো পুরো খেলাটা ঘুরে যাবে।'],petuk:['পেটুক চন্দ্র আগে দুটো কার্ড দেখে নিই, তারপর সিদ্ধান্ত!','খালি পেটে ষড়যন্ত্র চলে নাকি? কার্ড দাও!'],brahma:['ব্রহ্মদত্তের ঘাড় মটকানোর চাল—কে এবার বাঁচবে?','এই আক্রমণ থামানোর মতো ঢাল কারও নেই!'],betal:['বেতাল নেমেছে! আমার আক্রমণ কেউ ঠেকাতে পারবে না।','অন্ধকারে বেতালের চাল বোঝা সহজ নয়—সাবধান!'],kalu:['কালু ডাকাত হাজির—তোমার কয়েনের খবর কিন্তু আমি জানি!','দুই কয়েন রেখে লাভ কী? কালুর হাতে তুলে দাও!'],chor:['ছিঁচকে চোর চুপচাপ এসেছে—একজন নয়, সবার কয়েনেই নজর!','আমার চুরি ঠেকাতে হলে ছিঁচকে চোরই হতে হবে!'],nantu:['নান্টুমিয়ার খাজনা বাকি আছে—আজ কার পালা?','খাজনা বসালাম; আয় করলে এক কয়েন আমার ঘরে আসবেই!']};
export function CharacterVoice({claims,room}:{claims?:Game['claims'];room?:string}) {
 const [enabled,setEnabled]=useState(false),[available,setAvailable]=useState(false),[line,setLine]=useState('');
 const last=useRef('');
 useEffect(()=>{if(!('speechSynthesis' in window))return;const update=()=>setAvailable(speechSynthesis.getVoices().some(v=>v.lang.toLowerCase().startsWith('bn')));update();speechSynthesis.addEventListener('voiceschanged',update);return()=>{speechSynthesis.removeEventListener('voiceschanged',update);speechSynthesis.cancel()}},[]);
 useEffect(()=>{const c=claims?.at(-1);const key=room+':'+c?.id;const before=last.current;last.current=key;if(!enabled||!c||!before||key===before||document.visibilityState!=='visible')return;const choices=LINES[c.role];if(!choices)return;const text=choices[Math.floor(Math.random()*choices.length)];setLine(c.name+': '+text);const timer=setTimeout(()=>setLine(''),4200);const voice=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith('bn'));if(voice){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang=voice.lang;utterance.rate=.9;utterance.pitch=1.05;speechSynthesis.speak(utterance)}return()=>clearTimeout(timer)},[claims,room,enabled]);
 return <div className="character-voice"><button className="text-button" aria-pressed={enabled} onClick={()=>{setEnabled(v=>!v);setLine('');if('speechSynthesis' in window)speechSynthesis.cancel()}}>{enabled?'🔊 সংলাপ বন্ধ করুন':'🔈 চরিত্রের সংলাপ চালু করুন'}</button>{!available&&<small>বাংলা কণ্ঠ না থাকলে সংলাপ লেখা দেখাবে।</small>}{enabled&&line&&<p role="status">{line}</p>}</div>;
}
