'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {REACTIONS} from '@/lib/game/social';
import {feedbackSnapshot,personalEvent,type FeedbackGame} from '@/lib/game/feedback';

export function GameSocial({game,userId,busy,send,open,onOpenChange,showReactions}:{game:FeedbackGame|null;userId?:string;busy:boolean;open:boolean;onOpenChange:(v:boolean)=>void;showReactions:boolean;send:(reaction:string)=>Promise<boolean>}){
 const [reactionOpen,setReactionOpen]=useState(false),[sound,setSound]=useState(false),[vibration,setVibration]=useState(false),[supported,setSupported]=useState(false),[now,setNow]=useState(0),[sent,setSent]=useState(0),[audioError,setAudioError]=useState('');
 const audio=useRef<AudioContext|null>(null),last=useRef<ReturnType<typeof feedbackSnapshot>|null>(null);
 useEffect(()=>{setSupported('vibrate' in navigator);try{const p=JSON.parse(localStorage.getItem('sj-feedback-v1')??'{}');setSound(p.sound===true);setVibration(p.vibration===true)}catch{}const t=setInterval(()=>setNow(Date.now()),500);return()=>{clearInterval(t);void audio.current?.close()}},[]);
 const save=(s:boolean,v:boolean)=>{setSound(s);setVibration(v);try{localStorage.setItem('sj-feedback-v1',JSON.stringify({sound:s,vibration:v}))}catch{}};
 const unlock=()=>{try{const Audio=window.AudioContext??(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!Audio){setAudioError('এই ব্রাউজারে sound চালু করা যাচ্ছে না।');return}audio.current??=new Audio();void audio.current.resume().catch(()=>setAudioError('Sound চালু করতে আবার চাপুন।'));setAudioError('')}catch{setAudioError('এই ব্রাউজারে sound চালু করা যাচ্ছে না।')}};
 useEffect(()=>{if(!sound)return;const wake=()=>unlock();window.addEventListener('pointerdown',wake);window.addEventListener('keydown',wake);return()=>{window.removeEventListener('pointerdown',wake);window.removeEventListener('keydown',wake)}},[sound]);
 const play=(kind:'turn'|'coin'|'challenge'|'win'|'duel')=>{const ctx=audio.current;if(!sound||!ctx||ctx.state!=='running'||document.visibilityState!=='visible')return;const notes={turn:[440,660],coin:[880,1175],challenge:[220,165,330],win:[523,659,784,1047],duel:[659,880,659,523,440,330]}[kind];notes.forEach((frequency,i)=>{const start=ctx.currentTime+i*(kind==='duel'?.23:.12);const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type=kind==='duel'?'triangle':'sine';oscillator.frequency.setValueAtTime(frequency,start);if(kind==='duel')oscillator.frequency.exponentialRampToValueAtTime(frequency*.97,start+.3);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.065,start+.02);gain.gain.exponentialRampToValueAtTime(.001,start+(kind==='duel'?.4:.16));oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.45);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect()}})};
 useEffect(()=>{if(!game||!userId){last.current=null;return}const snapshot=feedbackSnapshot(game,userId),before=last.current;last.current=snapshot;if(!before)return;const fresh=before.room!==snapshot.room;const personal=personalEvent(fresh?{...snapshot,turn:0,response:0}:before,snapshot,userId);if(vibration&&navigator.vibrate&&personal&&document.visibilityState==='visible')navigator.vibrate(personal==='challenge'?[160,80,160]:personal==='win'?[180,90,240]:[180,90,180]);if(snapshot.duel&&(fresh||!before.duel))play('duel');else if(personal)play(personal);else if(!fresh&&snapshot.winner&&snapshot.winner!==before.winner)play('win');},[game,userId,sound,vibration]);
  const cooldown=now-sent<3000;
 return <><div className="social-controls">{showReactions&&game?.status==='playing'&&<button className="secondary" onClick={()=>setReactionOpen(true)} aria-label="Quick reaction পাঠান">☺ <span>প্রতিক্রিয়া</span></button>}</div><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>খেলার অনুভূতি</DialogTitle><DialogDescription>এই ডিভাইসের জন্য পছন্দ সংরক্ষিত থাকবে।</DialogDescription></DialogHeader><label className="feedback-setting"><span><strong>খেলার sound</strong><small>Duel-এর শুরুর সুর, নিজের সিদ্ধান্ত ও জয়ের সুর।</small></span><Switch checked={sound} onCheckedChange={v=>{save(v,vibration);if(v)unlock()}} aria-label="খেলার sound"/></label><label className="feedback-setting"><span><strong>Vibration</strong><small>{supported?'শুধু আপনার পালা, আপনার বিরুদ্ধে challenge, আক্রমণ ও চুরির ঘটনায়।':'এই ব্রাউজারে vibration সমর্থিত নয়।'}</small></span><Switch checked={vibration} disabled={!supported} onCheckedChange={v=>{save(sound,v);if(v)navigator.vibrate([180,90,180])}} aria-label="খেলার vibration"/></label>{audioError&&<p role="status">{audioError}</p>}<p className="small-note">Sound প্রথমে বন্ধ থাকে। চালু করে পাতায় চাপলে সুর বাজবে। Browser ও ফোনের সেটিংস অনুযায়ী vibration কাজ নাও করতে পারে।</p></DialogContent></Dialog><Dialog open={reactionOpen&&showReactions&&game?.status==='playing'} onOpenChange={setReactionOpen}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>একটি প্রতিক্রিয়া দিন</DialogTitle><DialogDescription>সব খেলোয়াড় ৬ সেকেন্ড দেখবে। দুটি প্রতিক্রিয়ার মাঝে ৩ সেকেন্ড বিরতি।</DialogDescription></DialogHeader><div className="reaction-picker">{REACTIONS.map(r=><button className="secondary" key={r.id} disabled={busy||cooldown} onClick={async()=>{if(await send(r.id)){setSent(Date.now());setReactionOpen(false)}}}><span>{r.emoji}</span>{r.text}</button>)}</div>{cooldown&&<p role="status">আরেকটি পাঠাতে একটু অপেক্ষা করুন…</p>}</DialogContent></Dialog></>;
}
