'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {REACTIONS} from '@/lib/game/social';
import type {Game} from '@/lib/game/engine';

type FeedbackGame=Pick<Game,'code'|'status'|'winner'|'turn'|'turnCount'|'series'|'reactions'> & {waiting:{eligible:string[];passed:string[]}|null;players:{id:string;coins:number;cards:{alive:boolean}[]}[];challenge?:Game['challenge']};
export function GameSocial({game,userId,busy,send}:{game:FeedbackGame|null;userId?:string;busy:boolean;send:(reaction:string)=>Promise<boolean>}){
 const [open,setOpen]=useState(false),[reactionOpen,setReactionOpen]=useState(false),[sound,setSound]=useState(false),[vibration,setVibration]=useState(false),[supported,setSupported]=useState(false),[now,setNow]=useState(0),[sent,setSent]=useState(0),[audioError,setAudioError]=useState('');
 const audio=useRef<AudioContext|null>(null),last=useRef<{room:string;coins:number;turn:boolean;challenge:string;winner:string|null}|null>(null);
 useEffect(()=>{setSupported('vibrate' in navigator);try{const p=JSON.parse(localStorage.getItem('sj-feedback-v1')??'{}');setSound(p.sound===true);setVibration(p.vibration===true)}catch{}const t=setInterval(()=>setNow(Date.now()),500);return()=>{clearInterval(t);void audio.current?.close()}},[]);
 const save=(s:boolean,v:boolean)=>{setSound(s);setVibration(v);try{localStorage.setItem('sj-feedback-v1',JSON.stringify({sound:s,vibration:v}))}catch{}};
 const unlock=()=>{try{const Audio=window.AudioContext??(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!Audio){setAudioError('এই ব্রাউজারে sound চালু করা যাচ্ছে না।');return}audio.current??=new Audio();void audio.current.resume().catch(()=>setAudioError('Sound চালু করতে আবার চাপুন।'));setAudioError('')}catch{setAudioError('এই ব্রাউজারে sound চালু করা যাচ্ছে না।')}};
 useEffect(()=>{if(!sound)return;const wake=()=>unlock();window.addEventListener('pointerdown',wake);window.addEventListener('keydown',wake);return()=>{window.removeEventListener('pointerdown',wake);window.removeEventListener('keydown',wake)}},[sound]);
 const play=(kind:'turn'|'coin'|'challenge'|'win')=>{if(document.visibilityState!=='visible')return;if(vibration&&navigator.vibrate)navigator.vibrate(kind==='challenge'?[140,70,140]:kind==='win'?[180,90,240]:kind==='turn'?[180,90,180]:80);const ctx=audio.current;if(!sound||!ctx||ctx.state!=='running')return;const notes={turn:[440,660],coin:[880,1175],challenge:[220,165,330],win:[523,659,784,1047]}[kind];notes.forEach((frequency,i)=>{const start=ctx.currentTime+i*.12;const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.07,start+.015);gain.gain.exponentialRampToValueAtTime(.001,start+.16);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.18);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect()}})};
 useEffect(()=>{if(!game||!userId){last.current=null;return}const me=game.players.find(p=>p.id===userId);const turn=game.status==='playing'&&(game.waiting?game.waiting.eligible.includes(userId)&&!game.waiting.passed.includes(userId):game.players[game.turn]?.id===userId);const snapshot={room:game.code+':'+(game.series?.round??1),coins:me?.coins??0,turn,challenge:game.challenge?String(game.challenge.id??game.turnCount):'',winner:game.winner};const before=last.current;last.current=snapshot;if(!before||before.room!==snapshot.room)return;if(snapshot.winner&&snapshot.winner!==before.winner)play('win');else if(snapshot.challenge&&snapshot.challenge!==before.challenge)play('challenge');else if(turn&&!before.turn)play('turn');else if(snapshot.coins>before.coins)play('coin');},[game,userId,sound,vibration]);
 const visible=(game?.reactions??[]).filter(r=>now-r.at<6000).slice(-3);
 const cooldown=now-sent<3000;
 return <><div className="social-controls"><button className="secondary" onClick={()=>setOpen(true)} aria-label="Sound ও vibration সেটিংস">⚙ <span>সেটিংস</span></button>{game&&<button className="secondary" onClick={()=>setReactionOpen(true)} aria-label="Quick reaction পাঠান">☺ <span>প্রতিক্রিয়া</span></button>}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>খেলার অনুভূতি</DialogTitle><DialogDescription>এই ডিভাইসের জন্য পছন্দ সংরক্ষিত থাকবে।</DialogDescription></DialogHeader><label className="feedback-setting"><span><strong>খেলার sound</strong><small>নিজের সিদ্ধান্তের সময়, কয়েন, challenge ও জয়ের সুর।</small></span><Switch checked={sound} onCheckedChange={v=>{save(v,vibration);if(v)unlock()}} aria-label="খেলার sound"/></label><label className="feedback-setting"><span><strong>Vibration</strong><small>{supported?'সমর্থিত ফোনে ছোট কম্পন।':'এই ব্রাউজারে vibration সমর্থিত নয়।'}</small></span><Switch checked={vibration} disabled={!supported} onCheckedChange={v=>{save(sound,v);if(v)navigator.vibrate([180,90,180])}} aria-label="খেলার vibration"/></label>{audioError&&<p role="status">{audioError}</p>}<p className="small-note">Sound প্রথমে বন্ধ থাকে। চালু করে পাতায় চাপলে সুর বাজবে। Browser ও ফোনের সেটিংস অনুযায়ী vibration কাজ নাও করতে পারে।</p></DialogContent></Dialog><Dialog open={reactionOpen} onOpenChange={setReactionOpen}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>একটি প্রতিক্রিয়া দিন</DialogTitle><DialogDescription>সব খেলোয়াড় ৬ সেকেন্ড দেখবে। দুটি প্রতিক্রিয়ার মাঝে ৩ সেকেন্ড বিরতি।</DialogDescription></DialogHeader><div className="reaction-picker">{REACTIONS.map(r=><button className="secondary" key={r.id} disabled={busy||cooldown} onClick={async()=>{if(await send(r.id)){setSent(Date.now());setReactionOpen(false)}}}><span>{r.emoji}</span>{r.text}</button>)}</div>{cooldown&&<p role="status">আরেকটি পাঠাতে একটু অপেক্ষা করুন…</p>}</DialogContent></Dialog></>;
}
