import {seriesResult} from './series';
import {REACTIONS,BOT_LEVELS} from './social';
import { chooseBotMove } from './bots';
import { bn, CARDS, card, DEFAULT_ROLES, type Role } from './cards';
export interface Player {botStyle?:'bold'|'careful'|'skeptic';lastReactionAt?:number;id:string;name:string;coins:number;cards:{role:Role;alive:boolean}[];ready:boolean;left?:boolean;bot?:boolean}
export interface Effect {type:string;actor?:string;target?:string;role?:Role;action?:string;amount?:number;targets?:string[];received?:number;primary?:string}
export interface ClaimRecord {id:number;round:number;turn:number;actor:string;name:string;role:Role;kind:string;target?:string;targetName?:string;challenger?:string;challengerName?:string;outcome:'pending'|'accepted'|'proven'|'bluff'|'withdrawn'}
export interface Series {total:number;round:number;results:{round:number;winner:string|null;name:string}[];scores:{id:string;name:string;wins:number}[]}
export interface Waiting {claimId?:number;type:'response'|'block'|'share'|'loss'|'exchange';actor:string;target?:string;role?:Role;kind?:string;eligible:string[];passed:string[];success:Effect[];failure:Effect[];deadline:number;message:string;options?:Role[];keep?:number;roles?:Role[]}
export interface RevealEvent {id:string;player:string;name:string;role:Role;at:number}
export interface Game {timers?:{turn:number;response:number;duel:number};attacks?:{id:string;actor:string;actorName:string;target:string;targetName:string;kind:string;at:number}[];reveals?:RevealEvent[];botDifficulty?:'easy'|'medium'|'hard';reactions?:{id:string;player:string;name:string;reaction:string;at:number}[];claims?:ClaimRecord[];claimSequence?:number;series?:Series;code:string;name:string;private:boolean;max:number;host:string;players:Player[];roles:Role[];status:'waiting'|'playing'|'finished';deck:Role[];turn:number;turnCount:number;deadline:number;waiting:Waiting|null;queue:Effect[];tax:{owner:string;role:Role}|null;log:{id:number;text:string}[];winner:string|null;revision:number;created:number;updated:number;botAt?:number;challenge?:{challenger:string;claimant:string;role:Role;truthful:boolean;id?:number}}
export class GameError extends Error {}
function fail(s:string):never{throw new GameError(s)}
export const alive=(p:Player)=>!p.left&&p.cards.some(c=>c.alive);
const living=(g:Game)=>g.players.filter(alive);
const player=(g:Game,id?:string)=>g.players.find(p=>p.id===id)??fail('খেলোয়াড় পাওয়া যায়নি।');
const log=(g:Game,text:string)=>{g.log.push({id:(g.log.at(-1)?.id??0)+1,text});g.log=g.log.slice(-70)};
const prepend=(g:Game,e:Effect[])=>g.queue.unshift(...e);
export function shuffle<T>(arr:T[]):T[]{for(let i=arr.length-1;i>0;i--){const a=new Uint32Array(1);const range=4294967296;const bound=range-range%(i+1);do{crypto.getRandomValues(a)}while(a[0]>=bound);const j=a[0]%(i+1);[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
export function newGame(code:string,name:string,isPrivate:boolean,max:number,host:string,displayName:string):Game{return {code,name,private:isPrivate,max,host,players:[{id:host,name:displayName,coins:2,cards:[],ready:false}],roles:[...DEFAULT_ROLES],status:'waiting',deck:[],turn:0,turnCount:0,deadline:0,waiting:null,queue:[],tax:null,log:[],winner:null,revision:0,created:Date.now(),updated:Date.now()}}
export function validRoles(roles:Role[]){return roles.length===5&&new Set(roles).size===5&&['blue','purple','black','green'].every((color)=>roles.filter(id=>CARDS.find(c=>c.id===id)?.color===color).length===(color==='green'?2:1))}
export function configureSeries(g:Game,total:number){if(g.status!=='waiting'||(g.series?.round??0)>0||![1,3,5,7].includes(total))fail('আসর শুরুর আগে ১, ৩, ৫ বা ৭ রাউন্ড বাছুন।');g.series={total,round:0,results:[],scores:[]};}
export function prepareRematch(g:Game){if(g.status!=='finished')fail('রাউন্ড শেষ হওয়ার অপেক্ষা করুন।');if(g.series&&seriesResult(g.series).complete)g.series={total:g.series.total,round:0,results:[],scores:[]};g.players=g.players.filter(p=>!p.left);g.status='waiting';g.players.forEach(p=>{p.ready=!!p.bot;p.cards=[];p.coins=2});g.waiting=null;g.queue=[];g.deck=[];g.winner=null;g.tax=null;g.challenge=undefined;}
function settleClaim(g:Game,w:Waiting,outcome:ClaimRecord['outcome'],challenger?:string){const c=g.claims?.find(c=>c.id===w.claimId);if(c){c.outcome=outcome;if(challenger){c.challenger=challenger;c.challengerName=player(g,challenger).name}}}
export function start(g:Game){if(g.players.length<2||g.players.length>6)fail('খেলতে মানুষ ও কম্পিউটার মিলিয়ে ২–৬ জন লাগবে।');if(!validRoles(g.roles))fail('১ নীল, ১ বেগুনি, ১ কালো ও ২ সবুজ চরিত্র বাছুন।');if(!g.players.every(p=>p.ready))fail('সব খেলোয়াড়কে প্রস্তুত হতে হবে।');g.series??={total:5,round:0,results:[],scores:[]};if(seriesResult(g.series).complete)fail('এই আসর শেষ। নতুন আসর খুলুন।');g.series.round++;for(const p of g.players){const score=g.series.scores.find(x=>x.id===p.id);if(score)score.name=p.name;else g.series.scores.push({id:p.id,name:p.name,wins:0})}g.claims=[];g.reveals=[];g.attacks=[];g.deck=shuffle(g.roles.flatMap(r=>[r,r,r]));g.players.forEach(p=>{p.coins=2;p.left=false;p.cards=[{role:g.deck.pop()!,alive:true},{role:g.deck.pop()!,alive:true}]});g.status='playing';g.turn=0;g.turnCount=1;g.tax=null;g.queue=[];g.waiting=null;g.winner=null;g.challenge=undefined;g.log=[];g.deadline=Date.now()+(living(g).length===2?(g.timers?.duel??30):(g.timers?.turn??60))*1000;log(g,'কার্ড দেওয়া হয়েছে। শুরু হোক ষড়যন্ত্র।');}
function checkWinner(g:Game){if(g.status!=='playing')return false;const survivors=living(g);if(survivors.length<=1){g.status='finished';g.winner=survivors[0]?.id??null;if(g.series&&!g.series.results.some(r=>r.round===g.series!.round)){g.series.results.push({round:g.series.round,winner:g.winner,name:survivors[0]?.name??'কেউ নয়'});const score=g.series.scores.find(s=>s.id===g.winner);if(score)score.wins++;}g.waiting=null;g.queue=[];log(g,survivors[0]?`${survivors[0].name} শেষ পর্যন্ত টিকে থেকে জয়ী!`:'টেবিলে কেউ নেই।');return true}return false}
function wait(g:Game,w:Omit<Waiting,'deadline'>){g.waiting={...w,deadline:Date.now()+(g.timers?.response??25)*1000}}
function response(g:Game,actor:string,role:Role,kind:string,success:Effect[],failure:Effect[],target?:string){const eligible=living(g).filter(p=>p.id!==actor).map(p=>p.id);if(!eligible.length){prepend(g,success);return}const claimId=(g.claimSequence??0)+1;g.claimSequence=claimId;g.claims??=[];g.claims.push({id:claimId,round:g.series?.round??1,turn:g.turnCount,actor,name:player(g,actor).name,role,kind,target,targetName:target?player(g,target).name:undefined,outcome:'pending'});g.claims=g.claims.slice(-300);wait(g,{claimId,type:'response',actor,target,role,kind,eligible,passed:[],success,failure,message:`${player(g,actor).name} ${card(role).name} দাবি করেছে${kind==='block'?'—ব্লক করতে':kind==='share'?'—ভাগ পেতে':''}${target?`। লক্ষ্য: ${player(g,target).name}`:''}।`})}
function tax(g:Game,actor:string,role:Role){const p=player(g,actor);if(g.tax&&g.tax.role===role&&g.tax.owner!==actor&&p.coins>0&&alive(player(g,g.tax.owner))){p.coins--;player(g,g.tax.owner).coins++;log(g,`${p.name} খাজনা হিসেবে ${player(g,g.tax.owner).name}-কে ১ কয়েন দিয়েছে।`)}}
function run(g:Game){let safety=0;while(g.status==='playing'&&!g.waiting&&g.queue.length){if(++safety>100)throw Error('Effect loop');const e=g.queue.shift()!;const p=e.actor?player(g,e.actor):null;
 if(e.type==='next'){if(checkWinner(g))return;do{g.turn=(g.turn+1)%g.players.length}while(!alive(g.players[g.turn]));g.turnCount++;g.deadline=Date.now()+(living(g).length===2?(g.timers?.duel??30):(g.timers?.turn??60))*1000;continue}
 if(e.type==='loss'){const target=player(g,e.target);if(!alive(target))continue;wait(g,{type:'loss',actor:target.id,eligible:[target.id],passed:[],success:[],failure:[],message:`${target.name}: ${e.action==='challenge'?'চ্যালেঞ্জে হারার জন্য':e.action==='bluff'?'মিথ্যা দাবি ধরা পড়ায়':'আক্রমণে'} একটি জীবিত কার্ড প্রকাশ করুন।`});continue}
 if(e.type==='transfer'){const t=player(g,e.target);if(p&&alive(p)&&alive(t)){const amount=Math.min(e.amount??0,t.coins);t.coins-=amount;p.coins+=amount;log(g,`${p.name}, ${t.name}-এর কাছ থেকে ${bn(amount)} কয়েন নিয়েছে।`)}continue}
 if(e.type==='tax'){if(p&&alive(p)&&e.role&&(e.amount===undefined||p.coins>e.amount))tax(g,p.id,e.role);continue}
 if(e.type==='theftTarget'){const t=player(g,e.target);if(!p||!alive(p)||!alive(t)||t.coins===0)continue;const options:Role[]=e.action==='kalu'?['kalu','petuk'].filter(r=>g.roles.includes(r as Role)) as Role[]:['chor'];wait(g,{type:'block',actor:t.id,role:e.action as Role,roles:options,eligible:[t.id],passed:[],success:[],failure:[{type:'transfer',actor:p.id,target:t.id,amount:e.amount}],message:`${t.name}: ${p.name}-কে ${bn(Math.min(e.amount!,t.coins))} কয়েন নিতে দেবেন, নাকি ব্লক করবেন?`});continue}
 if(e.type==='shareNext'){if(!p||!alive(p))continue;const targets=e.targets??[];const next=targets.shift();if(!next){prepend(g,[{type:'tax',actor:p.id,role:'mamdo'}]);continue}if(!alive(player(g,next))){prepend(g,[{...e,targets}]);continue}wait(g,{type:'share',actor:next,eligible:[next],passed:[],success:[{type:'sharePay',actor:next,primary:p.id,received:e.received??0},{...e,targets,received:(e.received??0)+1}],failure:[{...e,targets}],message:`${player(g,next).name}: মামদোহামদো দাবি করবেন${(e.received??0)<2?'—১ কয়েনের ভাগ পেতে':'? ভাগ বাকি নেই'}?`});continue}
 if(e.type==='sharePay'){const primary=player(g,e.primary);if(p&&alive(p)&&alive(primary)&&(e.received??0)<2&&primary.coins>0){primary.coins--;p.coins++;log(g,`${p.name}, ${primary.name}-এর কাছ থেকে ভাগের ১ কয়েন পেয়েছে।`);tax(g,p.id,'mamdo')}continue}
 if(e.type==='resolve'){if(!p||!alive(p))continue;switch(e.action){case 'income':p.coins++;log(g,`${p.name} সাধারণ আয় হিসেবে ১ কয়েন নিয়েছে।`);break;case 'kill':case 'brahma':case 'betal':if(e.target&&alive(player(g,e.target)))g.attacks=[...(g.attacks??[]),{id:crypto.randomUUID(),actor:p.id,actorName:p.name,target:e.target,targetName:player(g,e.target).name,kind:e.action,at:Date.now()}].slice(-8);prepend(g,[{type:'loss',target:e.target}]);break;case 'bir':p.coins+=3;log(g,`${p.name} ৩ কয়েন আয় করেছে।`);tax(g,p.id,'bir');break;case 'mamdo':{p.coins+=4;log(g,`${p.name} ভাগ দেওয়ার আগে ৪ কয়েন আয় করেছে।`);const index=g.players.findIndex(x=>x.id===p.id);const targets=Array.from({length:g.players.length-1},(_,i)=>g.players[(index+i+1)%g.players.length]).filter(alive).map(x=>x.id);prepend(g,[{type:'shareNext',actor:p.id,targets,received:0}]);break}case 'orun':case 'petuk':{const keep=p.cards.filter(c=>c.alive).length;const options=p.cards.filter(c=>c.alive).map(c=>c.role);for(let i=0;i<(e.action==='orun'?1:2);i++){const c=g.deck.pop();if(c)options.push(c)}wait(g,{type:'exchange',actor:p.id,eligible:[p.id],passed:[],success:[],failure:[],options,keep,message:`${p.name} রাখার জন্য ${bn(keep)}টি জীবিত কার্ড বেছে নিচ্ছে।`});break}case 'kalu':prepend(g,[{type:'theftTarget',actor:p.id,target:e.target,amount:2,action:'kalu'},{type:'tax',actor:p.id,role:'kalu',amount:p.coins}]);break;case 'chor':prepend(g,[...living(g).filter(x=>x.id!==p.id).map(x=>({type:'theftTarget',actor:p.id,target:x.id,amount:1,action:'chor'})),{type:'tax',actor:p.id,role:'chor',amount:p.coins}]);break;case 'nantu':g.tax={owner:p.id,role:e.role!};log(g,`${p.name}, ${card(e.role!).name}-এর ওপর ১ কয়েন খাজনা বসিয়েছে।`);break;} }
 }checkWinner(g)}
export function act(g:Game,id:string,input:{action:string;target?:string;role?:Role}){if(g.status!=='playing'||g.waiting||g.players[g.turn].id!==id)fail('নিজের পালার জন্য অপেক্ষা করুন।');const p=player(g,id);if(!alive(p))fail('আপনি এই রাউন্ড থেকে বাদ পড়েছেন।');const a=input.action;if(!['income','kill',...g.roles].includes(a))fail('এই চালটি এই ম্যাচে নেই।');if(p.coins>=10&&a!=='kill')fail('১০ কয়েন হলে ৭ কয়েনের হত্যা বাধ্যতামূলক।');if(['kill','brahma','betal','kalu'].includes(a)){const t=player(g,input.target);if(t.id===id||!alive(t))fail('অন্য একজন জীবিত খেলোয়াড় বেছে নিন।');}if(a==='nantu'&&(!input.role||!g.roles.includes(input.role)))fail('খাজনার জন্য একটি চরিত্র বেছে নিন।');const cost=a==='kill'?7:CARDS.find(c=>c.id===a)?.cost??0;if(p.coins<cost)fail('যথেষ্ট কয়েন নেই।');g.challenge=undefined;p.coins-=cost;log(g,`${p.name} ${a==='income'?'সাধারণ আয় বেছে নিয়েছে':a==='kill'?`৭ কয়েন দিয়ে ${player(g,input.target).name}-এর একটি জীবন নষ্ট করছে`:`${card(a).name} দাবি করেছে`}।`);g.queue=[{type:'next'}];const effect:Effect={type:'resolve',actor:id,action:a,target:input.target,role:input.role};if(a==='income'||a==='kill')prepend(g,[effect]);else response(g,id,a as Role,'action',[effect],[],['brahma','betal','kalu'].includes(a)?input.target:undefined);run(g)}
export function respond(g:Game,id:string,input:{choice:string;role?:Role;index?:number;indices?:number[]}){const w=g.waiting;if(g.status!=='playing'||!w||!w.eligible.includes(id)||w.passed.includes(id)||!alive(player(g,id)))fail('এই জবাব দেওয়ার সময় শেষ হয়েছে।');
 if(w.type==='response'){
 if(input.choice==='pass'){w.passed.push(id);log(g,`${player(g,id).name} ${w.kind==='block'?'ব্লক':'দাবি'} মেনে নিয়েছে।`);if(w.eligible.every(x=>w.passed.includes(x)||!alive(player(g,x)))){settleClaim(g,w,'accepted');g.waiting=null;prepend(g,w.success)}}
 else if(input.choice==='challenge'){const claimant=player(g,w.actor);const proof=claimant.cards.find(c=>c.alive&&c.role===w.role);settleClaim(g,w,proof?'proven':'bluff',id);g.challenge={id:w.claimId??g.turnCount,challenger:id,claimant:claimant.id,role:w.role!,truthful:!!proof};log(g,`${player(g,id).name}, ${claimant.name}-এর ${card(w.role!).name} দাবিকে চ্যালেঞ্জ করেছে।`);g.waiting=null;if(proof){const shown=proof.role;const attackWillHit=w.kind==='action'&&w.success.some(e=>e.type==='resolve'&&e.actor===claimant.id&&e.target===id&&(e.action==='brahma'||e.action==='betal'));const losses=1+(attackWillHit?1:0);const finalChallenge=living(g).length===2&&player(g,id).cards.filter(c=>c.alive).length<=losses;if(!finalChallenge){g.deck.push(shown);shuffle(g.deck);proof.role=g.deck.pop()!;}log(g,`${claimant.name}, ${card(shown).name} প্রমাণ করেছে। ${finalChallenge?'এই চ্যালেঞ্জ ও চালেই শেষ প্রতিপক্ষ বাদ পড়বে, তাই প্রমাণিত কার্ড বদলাবে না।':'ডেকে ফিরিয়ে নতুন কার্ড নিয়েছে।'} ${player(g,id).name} চ্যালেঞ্জে হেরেছে।`);prepend(g,[{type:'loss',target:id,action:'challenge'},...w.success])}else{log(g,`${player(g,id).name}, ${claimant.name}-এর ব্লাফ ধরে ফেলেছে!`);prepend(g,[{type:'loss',target:claimant.id,action:'bluff'},...w.failure])}}
 else fail('দাবি মানুন অথবা চ্যালেঞ্জ করুন।');
 }else if(w.type==='block'){g.waiting=null;if(input.choice==='block'){if(!input.role||!w.roles?.includes(input.role))fail('এই চরিত্র দিয়ে কাজটি ব্লক করা যায় না।');response(g,id,input.role,'block',[],w.failure)}else if(input.choice==='pass')prepend(g,w.failure);else fail('নিতে দিন অথবা ব্লক করুন।');
 }else if(w.type==='share'){g.waiting=null;if(input.choice==='claim')response(g,id,'mamdo','share',w.success,w.failure);else if(input.choice==='pass')prepend(g,w.failure);else fail('দাবি করুন অথবা ছেড়ে দিন।');
 }else if(w.type==='loss'){const p=player(g,id);const i=input.index;if(input.choice!=='lose'||!Number.isInteger(i)||!p.cards[i!]?.alive)fail('প্রকাশ করার জন্য একটি জীবিত কার্ড বেছে নিন।');p.cards[i!].alive=false;g.reveals=[...(g.reveals??[]),{id:crypto.randomUUID(),player:p.id,name:p.name,role:p.cards[i!].role,at:Date.now()}].slice(-12);log(g,`${p.name}, ${card(p.cards[i!].role).name} হারিয়েছে${alive(p)?'।':' এবং খেলা থেকে বাদ পড়েছে।'}`);if(g.tax?.owner===id&&!alive(p))g.tax=null;g.waiting=null;if(checkWinner(g))return;
 }else if(w.type==='exchange'){const indices=input.indices??[];if(input.choice!=='keep'||indices.length!==w.keep||new Set(indices).size!==indices.length||indices.some(i=>!Number.isInteger(i)||!w.options?.[i]))fail(`ঠিক ${bn(w.keep!)}টি কার্ড বেছে নিন।`);const p=player(g,id);const chosen=indices.map(i=>w.options![i]);let j=0;p.cards.forEach(c=>{if(c.alive)c.role=chosen[j++]});g.deck.push(...w.options!.filter((_,i)=>!indices.includes(i)));shuffle(g.deck);log(g,`${p.name} কার্ড অদলবদল শেষ করেছে।`);g.waiting=null;}
 run(g)}
export function tick(g:Game,now=Date.now(),allowBots=true){if(g.status!=='playing')return false;if(allowBots&&(g.botAt??0)<=now){const bot=g.waiting?g.players.find(p=>p.bot&&alive(p)&&g.waiting!.eligible.includes(p.id)&&!g.waiting!.passed.includes(p.id)):g.players[g.turn]?.bot?g.players[g.turn]:undefined;if(bot){const move=chooseBotMove(view(g,bot.id),bot.id);if(move){if(move.op==='act')act(g,bot.id,{action:move.action!,target:move.target,role:move.role});else respond(g,bot.id,{choice:move.choice!,role:move.role,index:move.index,indices:move.indices});g.botAt=now+1200;return true}}}const w=g.waiting;if(w&&w.deadline<=now){if(w.type==='response'){settleClaim(g,w,'accepted');g.waiting=null;prepend(g,w.success);log(g,'জবাবের সময় শেষ। দাবি গৃহীত হয়েছে।');run(g)}else if(w.type==='loss')respond(g,w.actor,{choice:'lose',index:player(g,w.actor).cards.findIndex(c=>c.alive)});else if(w.type==='exchange')respond(g,w.actor,{choice:'keep',indices:Array.from({length:w.keep!},(_,i)=>i)});else respond(g,w.actor,{choice:'pass'});return true}if(!w&&g.deadline<=now){const p=g.players[g.turn];log(g,`${p.name}-এর পালার সময় শেষ।`);act(g,p.id,{action:p.coins>=10?'kill':'income',target:living(g).find(x=>x.id!==p.id)?.id});return true}return false}
export function leave(g:Game,id:string){const p=player(g,id);if(!p.bot&&!g.players.some(x=>x.id!==id&&!x.bot&&!x.left)){g.host='';g.tax=null;g.waiting=null;g.queue=[];g.winner=null;if(g.status==='waiting'||g.status==='finished')g.players=[];else{g.players.forEach(x=>{x.left=true;x.cards.forEach(c=>c.alive=false)});g.status='finished'}return;}if(g.status==='waiting'||g.status==='finished'){g.players=g.players.filter(x=>x.id!==id);if(g.host===id)g.host=g.players.find(x=>!x.bot)?.id??'';return}if(g.waiting?.actor===id&&g.waiting.type==='exchange')respond(g,id,{choice:'keep',indices:Array.from({length:g.waiting.keep!},(_,i)=>i)});p.left=true;p.cards.forEach(c=>c.alive=false);log(g,`${p.name} রুম ছেড়ে বাকি জীবন হারিয়েছে।`);if(g.tax?.owner===id)g.tax=null;if(g.host===id)g.host=g.players.find(x=>!x.bot&&!x.left&&x.id!==id)?.id??'';if(checkWinner(g))return;const w=g.waiting;if(w){if(w.actor===id){if(w.type==='response')settleClaim(g,w,'withdrawn');g.waiting=null;prepend(g,w.type==='response'?w.failure:(w.type==='block'||w.type==='share')?w.failure:[])}else{w.eligible=w.eligible.filter(x=>x!==id);if(w.type==='response'&&w.eligible.every(x=>w.passed.includes(x)||!alive(player(g,x)))){settleClaim(g,w,'accepted');g.waiting=null;prepend(g,w.success)}}}else if(g.players[g.turn].id===id)prepend(g,[{type:'next'}]);run(g)}
export function phaseKey(g:Game){return [g.status,g.turnCount,g.turn,g.waiting?.type,g.waiting?.actor,g.waiting?.kind,g.waiting?.deadline??g.deadline].join(':')}
export function view(g:Game,id:string){return {...g,phase:phaseKey(g),deck:undefined,deckCount:g.deck.length,queue:undefined,players:g.players.map(p=>({...p,cards:p.cards.map(c=>({alive:c.alive,role:g.status==='finished'||p.id===id||!c.alive?c.role:null}))})),waiting:g.waiting?{...g.waiting,success:undefined,failure:undefined,options:g.waiting.actor===id?g.waiting.options:undefined}:null}}

export function setBotDifficulty(g:Game,level:string){if(g.status!=='waiting'||!Object.hasOwn(BOT_LEVELS,level))fail('খেলা শুরুর আগে সঠিক কম্পিউটার লেভেল বাছুন।');g.botDifficulty=level as Game['botDifficulty'];}
export function react(g:Game,id:string,reaction:string,now=Date.now()){const p=player(g,id);if(p.left||!REACTIONS.some(r=>r.id===reaction))fail('তালিকা থেকে একটি প্রতিক্রিয়া বাছুন।');if(now-(p.lastReactionAt??0)<3000)fail('আরেকটি প্রতিক্রিয়ার আগে ৩ সেকেন্ড অপেক্ষা করুন।');p.lastReactionAt=now;g.reactions=[...(g.reactions??[]).filter(r=>now-r.at<6000),{id:crypto.randomUUID(),player:id,name:p.name,reaction,at:now}].slice(-12);}
export function addBots(g:Game,count:number){if(g.status!=='waiting'||!Number.isInteger(count)||count<1||g.players.length+count>g.max)fail('খালি আসনের মধ্যে কম্পিউটারের সংখ্যা বাছুন।');for(let i=0;i<count;i++){let n=1;while(g.players.some(p=>p.name===`কম্পিউটার ${bn(n)}`))n++;g.players.push({id:'bot-'+crypto.randomUUID(),name:`কম্পিউটার ${bn(n)}`,bot:true,botStyle:(['bold','careful','skeptic'] as const)[(n-1)%3],coins:2,cards:[],ready:true})}}

export function configureTimers(g:Game,input?:unknown){
 if(g.status!=='waiting')fail('খেলা শুরুর আগে সময় বাছুন।');
 if(input===undefined)return;
 if(!input||typeof input!=='object')fail('সময়ের সেটিংস সঠিক নয়।');
 const t=input as Record<string,unknown>;
 for(const key of ['turn','response','duel'])if(typeof t[key]!=='number'||!Number.isInteger(t[key])||(t[key] as number)<10||(t[key] as number)>180)fail('সময় ১০–১৮০ সেকেন্ডের মধ্যে হতে হবে।');
 g.timers={turn:t.turn as number,response:t.response as number,duel:t.duel as number};
}
