import { rawDb } from '@/db/raw';
import { json,session,originCheck,rateLimit,cleanName,passwordHash } from '@/lib/server';
import { newGame,react,setBotDifficulty,configureSeries,prepareRematch,addBots,phaseKey,start,act,respond,tick,leave,view,validRoles,GameError,type Game } from '@/lib/game/engine';
interface Row{code:string;state:string;revision:number;password:string|null;updated:number}
const read=(code:string)=>rawDb().prepare('SELECT code,state,revision,password,updated FROM rooms WHERE code=?').bind(code).first<Row>();
const save=(g:Game,rev:number)=>{g.revision=rev+1;g.updated=Date.now();return rawDb().prepare('UPDATE rooms SET state=?,revision=?,updated=? WHERE code=? AND revision=?').bind(JSON.stringify(g),g.revision,g.updated,g.code,rev).run()};
function codeOf(v:unknown){if(typeof v!=='string'||! /^[A-Z2-9]{6}$/.test(v.toUpperCase()))throw Error('সঠিক ৬ অক্ষরের রুম কোড লিখুন।');return v.toUpperCase()}
function summary(g:Game){return {code:g.code,name:g.name,max:g.max,count:g.players.filter(p=>!p.left).length,status:g.status,roles:g.roles,private:g.private}}
export async function GET(req:Request){try{const s=await session(req);if(!s)return json({error:'সংযোগ করতে পাতা রিলোড করুন।'},401);const url=new URL(req.url);const code=url.searchParams.get('room');if(code){for(let i=0;i<4;i++){const row=await read(codeOf(code));if(!row||row.updated<Date.now()-86400000)return json({error:'রুম পাওয়া যায়নি অথবা মেয়াদ শেষ।'},404);const g:Game=JSON.parse(row.state);if(!g.players.some(p=>p.id===s.id&&!p.left))return json({error:'আগে এই রুমে যোগ দিন।'},403);if(tick(g)){const result=await save(g,row.revision);if(!result.meta.changes)continue}return json({game:view(g,s.id)})}return json({error:'রুম আপডেট হচ্ছে। আবার চেষ্টা করুন।'},409)}const rows=await rawDb().prepare('SELECT state FROM rooms WHERE private=0 AND updated>? ORDER BY updated DESC LIMIT 100').bind(Date.now()-86400000).all<{state:string}>();return json({rooms:rows.results.map((x:{state:string})=>JSON.parse(x.state) as Game).filter((g:Game)=>g.players.some(p=>!p.left)).map(summary)})}catch(e){console.error('Game read',e);return json({error:e instanceof Error?e.message:'রুমের তালিকা আনা যায়নি।'},400)}}
export async function POST(req:Request){try{originCheck(req);const s=await session(req);if(!s)return json({error:'আবার সংযোগ করতে পাতা রিলোড করুন।'},401);await rateLimit(s.id);const text=await req.text();if(text.length>6000)throw Error('অনুরোধটি অতিরিক্ত বড়।');const b=JSON.parse(text);if(b.op==='create'){
 const active=await rawDb().prepare("SELECT COUNT(*) n FROM rooms WHERE updated>? AND json_extract(state,'$.host')=? AND json_array_length(json_extract(state,'$.players'))>0").bind(Date.now()-86400000,s.id).first<{n:number}>();if((active?.n??0)>=5)throw Error('আপনার সাম্প্রতিক ৫টি রুম আছে। সেগুলোর একটিতে ফিরুন।');
 const name=cleanName(b.name);const max=Number(b.max);if(!Number.isInteger(max)||max<2||max>6)throw Error('২–৬টি আসন বেছে নিন।');const isPrivate=b.private===true;if(isPrivate&&(typeof b.password!=='string'||b.password.length<4||b.password.length>80))throw Error('পাসওয়ার্ড ৪–৮০ অক্ষরের হতে হবে।');const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=crypto.getRandomValues(new Uint8Array(6));const code=Array.from(bytes,x=>chars[x%chars.length]).join('');const g=newGame(code,name,isPrivate,max,s.id,s.name);configureSeries(g,b.rounds===undefined?5:Number(b.rounds));const salt=crypto.randomUUID();const password=isPrivate?`${salt}:${await passwordHash(b.password,salt)}`:null;await rawDb().prepare('INSERT INTO rooms (code,name,private,password,state,revision,updated) VALUES (?,?,?,?,?,0,?)').bind(code,name,isPrivate?1:0,password,JSON.stringify(g),Date.now()).run();return json({game:view(g,s.id)});
 }
 const code=codeOf(b.code);for(let retry=0;retry<4;retry++){const row=await read(code);if(!row||row.updated<Date.now()-86400000)return json({error:'রুম পাওয়া যায়নি অথবা মেয়াদ শেষ।'},404);const g:Game=JSON.parse(row.state);
 if(b.op==='join'){const existing=g.players.find(p=>p.id===s.id&&!p.left);if(existing)return json({game:view(g,s.id)});if(g.status!=='waiting')throw Error('এই ম্যাচ শুরু হয়ে গেছে।');if(g.players.length>=g.max)throw Error('এই রুমে আসন খালি নেই।');if(row.password){const [salt,hash]=row.password.split(':');if(typeof b.password!=='string'||b.password.length>80||await passwordHash(b.password,salt)!==hash)throw Error('রুমের পাসওয়ার্ড সঠিক নয়।');}g.players.push({id:s.id,name:s.name,coins:2,cards:[],ready:false});}
 else{const me=g.players.find(p=>p.id===s.id&&!p.left);if(!me)return json({error:'আপনি এই রুমের সদস্য নন।'},403);if(b.op!=='react'&&b.revision!==row.revision&&!(['act','respond'].includes(b.op)&&typeof b.phase==='string'&&b.phase===phaseKey(g)))return json({error:'টেবিলের অবস্থা বদলেছে। আবার চাল দিন।',game:view(g,s.id)},409);if(b.op!=='leave'&&b.op!=='react'&&tick(g,Date.now(),false)){const timed=await save(g,row.revision);return json({error:'সময় শেষ হওয়ায় খেলা এগিয়ে গেছে।',...(timed.meta.changes?{game:view(g,s.id)}:{})},409);}
 if(b.op==='leave')leave(g,s.id);
 else if(b.op==='react')react(g,s.id,b.reaction);
 else if(b.op==='botLevel'){if(g.host!==s.id)throw Error('শুধু হোস্ট কম্পিউটার লেভেল বাছতে পারে।');setBotDifficulty(g,b.level);g.players.forEach(p=>p.ready=!!p.bot);}
 else if(b.op==='ready'){if(g.status!=='waiting')throw Error('খেলা শুরু হয়ে গেছে।');me.ready=b.ready===true;}
 else if(b.op==='series'){if(g.host!==s.id)throw Error('শুধু হোস্ট রাউন্ড বাছতে পারে।');configureSeries(g,Number(b.rounds));g.players.forEach(p=>p.ready=!!p.bot);}
 else if(b.op==='roles'){if(g.host!==s.id||g.status!=='waiting')throw Error('খেলার আগে শুধু হোস্ট চরিত্র বাছতে পারে।');if(!Array.isArray(b.roles)||!validRoles(b.roles))throw Error('১ নীল, ১ বেগুনি, ১ কালো ও ২ সবুজ চরিত্র বাছুন।');g.roles=b.roles;g.players.forEach(p=>p.ready=!!p.bot);}
 else if(b.op==='bots'){if(g.host!==s.id)throw Error('শুধু হোস্ট কম্পিউটার যোগ করতে পারে।');addBots(g,Number(b.count));}
 else if(b.op==='kick'){if(g.host!==s.id||g.status!=='waiting'||b.target===s.id)throw Error('খেলার আগে শুধু হোস্ট অন্য খেলোয়াড় সরাতে পারে।');leave(g,b.target);}
 else if(b.op==='start'){if(g.host!==s.id||g.status!=='waiting')throw Error('শুধু হোস্ট অপেক্ষমান খেলা শুরু করতে পারে।');start(g);}
 else if(b.op==='rematch'){if(g.host!==s.id||g.status!=='finished')throw Error('খেলা শেষে শুধু হোস্ট নতুন রাউন্ড খুলতে পারে।');prepareRematch(g);}
 else if(b.op==='act')act(g,s.id,{action:b.action,target:b.target,role:b.role});
 else if(b.op==='respond')respond(g,s.id,{choice:b.choice,role:b.role,index:b.index,indices:b.indices});else throw Error('চালটি সঠিক নয়।');
 }
 const result=await save(g,row.revision);if(result.meta.changes)return json(b.op==='leave'?{left:true}:{game:view(g,s.id)});if(!['join','act','respond','react'].includes(b.op))return json({error:'অন্য খেলোয়াড় আগে চাল দিয়েছে। আবার চেষ্টা করুন।'},409);
 }return json({error:'টেবিল আপডেট হচ্ছে। আবার চেষ্টা করুন।'},409);
 }catch(e){if(!(e instanceof GameError))console.error('Game request',e);return json({error:e instanceof Error?e.message:'চালটি সম্পন্ন করা যায়নি।'},400)}}
